GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO contable_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO contable_user;
GRANT USAGE, CREATE ON SCHEMA public TO contable_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO contable_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO contable_user;
